AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec
    - sam.gemspec

Metrics/LineLength:
  Exclude:
    - sam.gemspec

Style/Documentation:
  Enabled: false