AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - !ruby/regexp /.*_spec\.rb$/
    - sam.gemspec

Metrics/LineLength:
  Exclude:
    - sam.gemspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
